name: test building greentea tests with cmake

on: [pull_request]

jobs:
  build-greentea-cmake:
    runs-on: ubuntu-latest
    container: ghcr.io/armmbed/mbed-os-env:master-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python3-venv
        run: |
          apt-get update
          apt-get install -y python3-venv

      - name: Build NUCLEO_G031K8 with baremetal profile
        run: |
            rm -rf __build
            cmake -S . -B __build -GNinja -DCMAKE_CTEST_ARGUMENTS="--output-on-failure;-V" -DMBED_BUILD_GREENTEA_TESTS=ON -DMBED_GREENTEA_TEST_BAREMETAL=ON -DMBED_GREENTEA_SERIAL_PORT=/dev/ttyDUMMY -DMBED_TARGET=NUCLEO_G031K8 -DMBED_APP_JSON_PATH=TESTS/configs/baremetal.json
            cmake --build __build

      - name: Build ARM_MUSCA_S1 with full profile
        run: |
            rm -rf __build
            cmake -S . -B __build -GNinja -DCMAKE_CTEST_ARGUMENTS="--output-on-failure;-V" -DMBED_BUILD_GREENTEA_TESTS=ON -DMBED_GREENTEA_SERIAL_PORT=/dev/ttyDUMMY -DMBED_TARGET=ARM_MUSCA_S1
            cmake --build __build
