#include "mail_generated.h" // This was generated by `flatc`.

using namespace Mail; // Specified in the schema.

// Create a `FlatBufferBuilder`, which will be used to create our
// monsters' FlatBuffers.
flatbuffers::FlatBufferBuilder builder(1024);

// Value voltages[] = { Value(100, 50, 30), Value(20, 10, 30) };
// auto inputs = builder.CreateVectorOfStructs(voltages, 2);

// float classification_values[]={1.4f,1.8f,13.4f};
// auto classification = builder.CreateVector(classification_values,4);

// auto orc = CreateMail(builder, inputs, classification, 1, 1);

// builder.Finish(orc);

// // This must be called after `Finish()`.
// uint8_t *buf = builder.GetBufferPointer();
// int size = builder.GetSize(); // Returns the size of the buffer that
//                               // `GetBufferPointer()` points to.
